import Head from "next/head";
import styles from "../styles/Home.module.css";

import Header from "../components/header";
import TokenComp from "../components/token";

export default function Token() {
  return (
    <section className={styles.container}>
      <Head>
        <title>Web 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <TokenComp />
      </main>
    </section>
  );
}


// export async function getServerSideProps() {
//   const response = await fetch("/api/moralis");
//   const data = await response.json();

//   return {
//     props: {
//       balances: data.raw,
//     },
//   };
// }